apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80

  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}

      - setWeight: 40
      - pause: {}

      - setWeight: 60
      - pause: {}

      - setWeight: 100
